sudo: required
services:
    - docker

before_install:
    - travis_wait docker build  -t eldrissi/docker-react -f Dockerfile.dev . 

script:
    - travis_wait docker run eldrissi/docker-react npm run test -- --coverage
